name: build-plugin
on:
  workflow_dispatch:

jobs:
  build-win-plugin:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./rust/
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path rust/Cargo.toml --release

      - name: Temporary store plugin
        uses: actions/upload-artifact@v3
        with:
          name: com.dim.streamdeck.exe
          path: ./rust/target/release/plugin.exe
          retention-days: 1

  build-mac-plugin:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./rust/
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
            command: build
            args: --manifest-path rust/Cargo.toml --release

      - name: Temporary store plugin
        uses: actions/upload-artifact@v3
        with:
          name: com.dim.streamdeck
          path: ./rust/target/release/plugin
          retention-days: 1

