name: build-plugin
on:
  workflow_dispatch:

jobs:
  build-win-plugin:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./rust/
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --manifest-path rust/Cargo.toml --release

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --manifest-path solo-mode-service/Cargo.toml --release

      - name: Temporary store plugin
        uses: actions/upload-artifact@v3
        with:
          name: com.dim.streamdeck.exe
          path: ./rust/target/release/plugin.exe
          retention-days: 10

      - name: Temporary store install-sd-solo-enabler.exe
        uses: actions/upload-artifact@v3
        with:
          name: service-installer
          path: ./solo-mode-service/target/release/install-sd-solo-enabler.exe
          retention-days: 10

      - name: Temporary store remove-sd-solo-enabler.exe
        uses: actions/upload-artifact@v3
        with:
          name: service-remover
          path: ./solo-mode-service/target/release/remove-sd-solo-enabler.exe
          retention-days: 10

      - name: Temporary store sd-solo-enabler.exe
        uses: actions/upload-artifact@v3
        with:
          name: service
          path: ./solo-mode-service/target/release/sd-solo-enabler.exe
          retention-days: 10

  build-mac-plugin:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./rust/
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1.0.1
        with:
            command: build
            args: --manifest-path rust/Cargo.toml --release

      - name: chmod +x
        run: chmod +x ./target/release/plugin

      - name: Temporary store plugin
        uses: actions/upload-artifact@v3
        with:
          name: com.dim.streamdeck
          path: ./rust/target/release/plugin
          retention-days: 10

